// Generated by LiveScript 1.4.0
(function(){
  var backbone, http, express, ejslocals, h, _, util, colors;
  backbone = require('backbone4000');
  http = require('http');
  express = require('express');
  ejslocals = require('ejs-locals');
  h = require('helpers');
  _ = require('underscore');
  util = require('util');
  colors = require('colors');
  exports.lego = backbone.Model.extend4000({
    requires: ['logger'],
    after: ['db'],
    init: function(callback){
      var app, ref$, ref1$, ref2$, ref3$, ref4$, ref5$, ref6$, ref7$, this$ = this;
      this.env.app = app = express();
      this.settings = _.extend({
        'static': h.path(this.env.root, 'static'),
        views: h.path(this.env.root, 'ejs'),
        port: 80,
        log: true
      }, this.settings);
      if (this.settings.log) {
        app.use(function(req, res, next){
          var host, forwarded;
          host = req.socket.remoteAddress;
          if (host === "127.0.0.1") {
            if (forwarded = req.headers['x-forwarded-for']) {
              host = forwarded;
            }
          }
          req.logContext = {
            tags: ['ip-' + host]
          };
          this$.env.log(req.originalUrl + " [" + req.headers['user-agent'] + "]", {
            url: req.originalUrl,
            ip: host,
            headers: req.headers,
            method: req.method
          }, 'http', req.method, "ip-" + host);
          return next();
        });
      }
      if (this.settings.configure) {
        this.settings.configure(app);
      } else {
        app.engine('ejs', ejslocals);
        app.set('view engine', 'ejs');
        app.set('views', (ref$ = this.env) != null ? (ref1$ = ref$.settings) != null ? (ref2$ = ref1$.module) != null ? (ref3$ = ref2$.express4) != null ? ref3$.views : void 8 : void 8 : void 8 : void 8) || __dirname + '/ejs';
        app.set('x-powered-by', false);
        app.use(express['static'](((ref4$ = this.env) != null ? (ref5$ = ref4$.settings) != null ? (ref6$ = ref5$.module) != null ? (ref7$ = ref6$.express4) != null ? ref7$['static'] : void 8 : void 8 : void 8 : void 8) || __dirname + '/static', {
          index: false,
          redirect: false,
          etag: false,
          dotfiles: 'ignore'
        }));
      }
      this.env.http = http.createServer(this.env.app);
      this.env.http.listen(this.settings.port);
      this.env.log('express listening at ' + colors.green(this.settings.port), {}, 'init', 'ok');
      return callback();
    }
  });
}).call(this);
